//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainerApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainerApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a single hit in any enemy will fill the Chaos Bar and enable you to use the Chaos Form..
        /// </summary>
        public static string strChkCheatDescriptionEasyChaosForm {
            get {
                return ResourceManager.GetString("strChkCheatDescriptionEasyChaosForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kill enemies with a single hit..
        /// </summary>
        public static string strChkCheatDescriptionEasyKills {
            get {
                return ResourceManager.GetString("strChkCheatDescriptionEasyKills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to receive infinite Blue Souls to buy anything with Vulgrim!.
        /// </summary>
        public static string strChkCheatDescriptionInfiniteBlueSouls {
            get {
                return ResourceManager.GetString("strChkCheatDescriptionInfiniteBlueSouls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to player&apos;s Health Points are frozen..
        /// </summary>
        public static string strChkCheatDescriptionInfiniteHP {
            get {
                return ResourceManager.GetString("strChkCheatDescriptionInfiniteHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can make your horse sprint unlimitedly!.
        /// </summary>
        public static string strChkCheatDescriptionInfiniteRuinSprints {
            get {
                return ResourceManager.GetString("strChkCheatDescriptionInfiniteRuinSprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to have unlimited Wrath to use War&apos;s special powers at any time!.
        /// </summary>
        public static string strChkCheatDescriptionInfiniteWrath {
            get {
                return ResourceManager.GetString("strChkCheatDescriptionInfiniteWrath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hit any enemy with a weapon, and that weapon will level-up to its maximum level instantaneously!.
        /// </summary>
        public static string strChkCheatDescriptionWeaponsEasyLevelUp {
            get {
                return ResourceManager.GetString("strChkCheatDescriptionWeaponsEasyLevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Chaos Form:.
        /// </summary>
        public static string strChkCheatPromptEasyChaosForm {
            get {
                return ResourceManager.GetString("strChkCheatPromptEasyChaosForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy kills:.
        /// </summary>
        public static string strChkCheatPromptEasyKills {
            get {
                return ResourceManager.GetString("strChkCheatPromptEasyKills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite Blue Souls:.
        /// </summary>
        public static string strChkCheatPromptInfiniteBlueSouls {
            get {
                return ResourceManager.GetString("strChkCheatPromptInfiniteBlueSouls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite HP:.
        /// </summary>
        public static string strChkCheatPromptInfiniteHP {
            get {
                return ResourceManager.GetString("strChkCheatPromptInfiniteHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite Ruin&apos;s sprints:.
        /// </summary>
        public static string strChkCheatPromptInfiniteRuinSprints {
            get {
                return ResourceManager.GetString("strChkCheatPromptInfiniteRuinSprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite Wrath:.
        /// </summary>
        public static string strChkCheatPromptInfiniteWrath {
            get {
                return ResourceManager.GetString("strChkCheatPromptInfiniteWrath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons Easy Level-Up:.
        /// </summary>
        public static string strChkCheatPromptWeaponsEasyLevelUp {
            get {
                return ResourceManager.GetString("strChkCheatPromptWeaponsEasyLevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available hacks.
        /// </summary>
        public static string strGroupBoxHeaderCheats {
            get {
                return ResourceManager.GetString("strGroupBoxHeaderCheats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game info.
        /// </summary>
        public static string strGroupBoxHeaderGameInfo {
            get {
                return ResourceManager.GetString("strGroupBoxHeaderGameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support us!.
        /// </summary>
        public static string strGroupBoxHeaderSupport {
            get {
                return ResourceManager.GetString("strGroupBoxHeaderSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Click to donate via PayPal)..
        /// </summary>
        public static string strLblClickToDonate {
            get {
                return ResourceManager.GetString("strLblClickToDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game&apos;s process:.
        /// </summary>
        public static string strLblGamesProcessPrompt {
            get {
                return ResourceManager.GetString("strLblGamesProcessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game not detected... Please, run the game!.
        /// </summary>
        public static string strLblNotAttached {
            get {
                return ResourceManager.GetString("strLblNotAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID:.
        /// </summary>
        public static string strLblProcessIDPrompt {
            get {
                return ResourceManager.GetString("strLblProcessIDPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, consider supporting the developer!.
        /// </summary>
        public static string strLblRequestForDonation {
            get {
                return ResourceManager.GetString("strLblRequestForDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required game version:.
        /// </summary>
        public static string strLblRequiredGameVersionPrompt {
            get {
                return ResourceManager.GetString("strLblRequiredGameVersionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1.
        /// </summary>
        public static string strLblRequiredGameVersionValue {
            get {
                return ResourceManager.GetString("strLblRequiredGameVersionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAMvader-Darksiders by Vinicius.RAS.
        /// </summary>
        public static string strMainWindowTitle {
            get {
                return ResourceManager.GetString("strMainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to attach to the game&apos;s process!.
        /// </summary>
        public static string strMsgFailedToAttach {
            get {
                return ResourceManager.GetString("strMsgFailedToAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to attach.
        /// </summary>
        public static string strMsgFailedToAttachCaption {
            get {
                return ResourceManager.GetString("strMsgFailedToAttachCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NONE&gt;.
        /// </summary>
        public static string strNoneTag {
            get {
                return ResourceManager.GetString("strNoneTag", resourceCulture);
            }
        }
    }
}
